// Package bootstrap generates the self-extracting POSIX sh script that
// carries the duffel and the rc wrapper that loads it.
//
// The script is the whole deployment story: it travels inside a single
// ssh/exec argument, extracts the payload into a private mktemp -d,
// runs your shell (or a one-off command), and removes the tempdir the
// moment the shell exits — enforced by a trap, and never defeated by
// exec-ing the shell away. The contract is documented in
// docs/bootstrap-protocol.md and every clause of it is tested.
package bootstrap

import (
	"encoding/base64"
	"fmt"
	"strings"

	"github.com/JaydenCJ/dotduffel/internal/manifest"
	"github.com/JaydenCJ/dotduffel/internal/version"
)

// Exit codes reserved by the bootstrap script itself. They sit at the
// top of the 8-bit range so they cannot collide with common tool codes.
const (
	ExitExtractFailed = 95 // tar could not unpack the payload
	ExitNoDecoder     = 96 // no base64/openssl decoder on the host
	ExitNoTempdir     = 97 // mktemp -d failed
)

// Options configures script generation.
type Options struct {
	Payload []byte // the tar.gz bundle (already includes the rc wrapper)
	Shell   string // "bash" or "sh"
	Command string // non-empty: run this and exit instead of an interactive shell
}

// Script renders the complete bootstrap. It is pure text generation:
// same options in, same script out.
func Script(o Options) string {
	b64 := base64.StdEncoding.EncodeToString(o.Payload)
	var b strings.Builder
	fmt.Fprintf(&b, "# dotduffel %s — self-extracting, self-cleaning shell bundle\n", version.Version)
	b.WriteString("# Runs on the target host: extracts into a private tempdir, starts your\n")
	b.WriteString("# shell, and removes every trace when it exits. Nothing is installed.\n")
	b.WriteString("set -u\n")
	b.WriteString(`duffel_dir="$(mktemp -d "${TMPDIR:-/tmp}/duffel.XXXXXXXX")" || exit ` + itoa(ExitNoTempdir) + "\n")
	b.WriteString(`trap 'rm -rf "$duffel_dir"' EXIT HUP INT TERM` + "\n")
	b.WriteString("duffel_b64='" + b64 + "'\n")
	// Decoder ladder: GNU/busybox base64 -d, then BSD base64 -D, then
	// openssl. Failed attempts truncate-overwrite, so a half-written
	// payload from one branch cannot leak into the next.
	b.WriteString(`if printf %s "$duffel_b64" | base64 -d >"$duffel_dir/payload.tgz" 2>/dev/null; then :` + "\n")
	b.WriteString(`elif printf %s "$duffel_b64" | base64 -D >"$duffel_dir/payload.tgz" 2>/dev/null; then :` + "\n")
	b.WriteString(`elif command -v openssl >/dev/null 2>&1; then` + "\n")
	b.WriteString(`  printf %s "$duffel_b64" | openssl base64 -d -A >"$duffel_dir/payload.tgz" || exit ` + itoa(ExitNoDecoder) + "\n")
	b.WriteString("else\n")
	b.WriteString(`  echo 'dotduffel: no base64 decoder on this host' >&2` + "\n")
	b.WriteString("  exit " + itoa(ExitNoDecoder) + "\n")
	b.WriteString("fi\n")
	b.WriteString("unset duffel_b64\n")
	b.WriteString(`tar -xzf "$duffel_dir/payload.tgz" -C "$duffel_dir" 2>/dev/null || { echo 'dotduffel: payload extraction failed' >&2; exit ` + itoa(ExitExtractFailed) + `; }` + "\n")
	b.WriteString(`rm -f "$duffel_dir/payload.tgz"` + "\n")
	b.WriteString(`DUFFEL_DIR="$duffel_dir"` + "\n")
	b.WriteString("export DUFFEL_DIR\n")
	b.WriteString(runLine(o.Shell, o.Command))
	// Deliberately no exec: the wrapper must outlive the shell so the
	// EXIT trap can remove the tempdir. exec would orphan the trap.
	b.WriteString("duffel_status=$?\n")
	b.WriteString("exit $duffel_status\n")
	return b.String()
}

func runLine(shell, command string) string {
	if command != "" {
		// The rc wrapper and the command sit on separate lines so that
		// aliases defined while sourcing are visible when the command
		// line is parsed; -O expand_aliases makes bash honor them in
		// non-interactive mode (sh expands aliases unconditionally).
		inner := `. "$DUFFEL_DIR/` + manifest.RCName + `"` + "\n" + command
		if shell == "sh" {
			return "sh -c " + ShellQuote(inner) + "\n"
		}
		return "bash -O expand_aliases -c " + ShellQuote(inner) + "\n"
	}
	if shell == "sh" {
		// POSIX sh has no --rcfile; ENV is the standard interactive hook.
		return `ENV="$duffel_dir/` + manifest.RCName + `" sh -i` + "\n"
	}
	return `bash --rcfile "$duffel_dir/` + manifest.RCName + `" -i` + "\n"
}

// RCFile renders the wrapper that runs in place of the remote rc file.
// Host defaults load first (your duffel augments the box, it does not
// replace it), then a bundled bin/ joins PATH, env pins apply, and
// finally the user's entry file is sourced.
func RCFile(m manifest.Manifest) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# generated by dotduffel %s — sourced in place of the remote rc file\n", version.Version)
	if m.Shell == "sh" {
		b.WriteString(`[ -f "$HOME/.shrc" ] && . "$HOME/.shrc"` + "\n")
	} else {
		b.WriteString(`[ -f /etc/bash.bashrc ] && . /etc/bash.bashrc` + "\n")
		b.WriteString(`[ -f "$HOME/.bashrc" ] && . "$HOME/.bashrc"` + "\n")
	}
	b.WriteString(`if [ -d "$DUFFEL_DIR/bin" ]; then` + "\n")
	b.WriteString(`  PATH="$DUFFEL_DIR/bin:$PATH"` + "\n")
	b.WriteString("  export PATH\n")
	b.WriteString("fi\n")
	for _, kv := range manifest.SortedEnv(m) {
		k, v, _ := strings.Cut(kv, "=")
		b.WriteString("export " + k + "=" + ShellQuote(v) + "\n")
	}
	b.WriteString(`[ -f "$DUFFEL_DIR/` + m.Entry + `" ] && . "$DUFFEL_DIR/` + m.Entry + `"` + "\n")
	// An interactive rc file must not leave a failing status behind.
	b.WriteString("true\n")
	return b.String()
}

// safeChars are the characters that need no quoting in POSIX sh.
const safeChars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789@%_+=:,./-"

// ShellQuote renders s as a single POSIX sh word: empty strings become a
// pair of single quotes, unsafe strings are single-quoted with embedded
// single quotes escaped via the standard quote-backslash-quote dance.
func ShellQuote(s string) string {
	if s == "" {
		return "''"
	}
	safe := true
	for _, r := range s {
		if !strings.ContainsRune(safeChars, r) {
			safe = false
			break
		}
	}
	if safe {
		return s
	}
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// QuoteArgv renders an argv as a copy-pasteable shell command line.
func QuoteArgv(argv []string) string {
	parts := make([]string, len(argv))
	for i, a := range argv {
		parts[i] = ShellQuote(a)
	}
	return strings.Join(parts, " ")
}

func itoa(n int) string { return fmt.Sprintf("%d", n) }
